# profile/config.yaml

# General snakemake parameters
use-conda: false
use-singularity: true
use-envmodules: true
printshellcmds: true
latency-wait: 100
nolock: true
conda-frontend: conda
jobs: 50

# Slurm parameters
slurm: True

# Default slurm resources
default-resources:
  - slurm_account=esnitkin1
  - slurm_partition=standard
  - runtime=90
  - mem_mb=5000

local-cores: 1
rerun-incomplete: true
